#include "Renderer.h"
#include "Environment.h" // <- generated by cmake
#include "StreamRedirector.h"

#include <gtest/gtest.h>

using namespace rprf;

struct TestRenderer : public ::testing::Test
{
    void SetUp()
    {
    }

    void TearDown()
    {
    }
};

TEST_F(TestRenderer, initialization)
{
	EXPECT_EQ(0, 0);
	EXPECT_TRUE(true);
}
